server:
  forward-headers-strategy: native

spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql-23e0c09-walter-5960.i.aivencloud.com:15139/lifelog?ssl-mode=REQUIRED
    username: ENC(AYMbwzwz6yKQM/YzEKnvng==)
    password: ENC(Ckfh13n/jh2gUJ2futzT3UyE0yCNB2AQRI5riQ6bWlI=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    show-sql: false
  data:
    mongodb:
      auto-index-creation: true
    redis:
      ssl:
        enabled: true
      url: ENC(kn1sVpDdQFXlxdV3EPeiovoI5FVPxl/FiAaJu/23CHr5JZ2hbRhAvl0rS6SSvFWPJ/9hXH6g+lmjJ/cC24ErAYiUPxR5zVe2TEXoZAYsUgW/AJ/RdagibQ8aUqgKc4eQDb/EZ5vGvZc=)
      timeout: 2m
      connect-timeout: 10s
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 2
        options:
          socket-options:
            keep-alive: true
            tcp-no-delay: true
  mongodb:
    uri: ENC(oX46Cs3JsnnonBdNyJCAs2Z4ncCnYZMJena1oELToD90DGOoYCfIXNBwG1+k5e1tXHEiH4ckDxqJzXKBe/tIycpfPJtaITwsj2hq8jP78Nb4yUKqpqb7HBHegBuz/CZTeuWoCbttwBT561zNp98mFw==)
  kafka:
    bootstrap-servers: ENC(wyTduAvWedQpTkk2SaFse80688ygBV089qtxsKTkLhOYjFmpTJsLk1Lzxp92poLasm+AbWWD5GzHppaqCVSUng==)
  thymeleaf:
    cache: true

# Kafka SSL 인증서 파일 경로 - 로컬 테스트 시 classpath:path/, 서버 경로에 배치 시 file:path/ 에 파일 경로 설정
kafka:
  ssl:
    key-location:
    certificate-location:
    ca-location:

management:
  tracing:
    export:
      enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://127.0.0.1:4318/v1/traces

logging:
  level:
    root: INFO
    com.walter.lifelog: INFO
    org.hibernate.SQL: WARN
    org.springframework: WARN
